# Generated by Django 2.0.7 on 2018-09-24 20:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=250)),
                ('bindto', models.CharField(choices=[('Client', 'Client'), ('Employee', 'Employee')], max_length=1, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Published', 'Publish'), ('Draft', 'Draft')], max_length=250, verbose_name='Status')),
            ],
        ),
    ]
