# Generated by Django 2.0.7 on 2018-09-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmanagement',
            name='bindto',
            field=models.CharField(choices=[('Client', 'Client'), ('Employee', 'Employee')], max_length=30, null=True),
        ),
    ]
