# Generated by Django 5.1.6 on 2025-02-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
