# Generated by Django 5.1.6 on 2025-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Judge", "Judge"),
                    ("Advocate", "Advocate"),
                    ("Lawyer", "Lawyer"),
                    ("Normal", "Normal User"),
                ],
                default="Normal",
                max_length=20,
            ),
        ),
    ]
