# Generated by Django 2.0.7 on 2018-09-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmanagements',
            name='orginization',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Organizations'),
        ),
    ]
