# Generated by Django 2.0.7 on 2018-10-02 19:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contactsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanagements',
            name='address',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='contactmanagements',
            name='city',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='contactmanagements',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='contactmanagements',
            name='postcode',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='contactmanagements',
            name='state',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='contactmanagements',
            name='street',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
