# Generated by Django 2.0.7 on 2018-09-23 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanagements',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
