# Generated by Django 2.0.7 on 2018-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsmanagement', '0002_auto_20181002_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanagements',
            name='note',
            field=models.TextField(default=None, max_length=2048),
        ),
    ]
